dist: trusty
sudo: false
language: node_js
node_js:
  - node
  - 10
  - 8
script:
  - npm run build
  - npm test
after_success:
  - npx codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
