dist: trusty
sudo: false
language: node_js
node_js:
  - node
  - 10
  - 8
after_success:
  - npx -p grunt-cli grunt coverage
  - npx istanbul report text-summary lcov
  - npx codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
