sudo: false
language: node_js
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
node_js:
  - node
  - 4
  - 0.12
before_install:
  # install NPM 2
  - npm i -g npm@^2.0.0
after_success:
  - grunt coverage
  - istanbul report text-summary lcov
  - cat ./coverage/lcov.info | coveralls
  - grunt build
  # install travis-after-all script to enable running `semantic-release` after ALL build succeed
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  # run `semantic-release` exactly once after all builds pass
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
