sudo: false
language: node_js
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
node_js:
  - '0.12'
  - '0.10'
after_success:
  - grunt coverage
  - istanbul report text-summary lcov
  - cat ./coverage/lcov.info | coveralls
notifications:
  webhooks: http://webhook.hakatashi.com/travis
